---
title: "Chapter 3 hw"
output: html_document
date: "2025-01-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
```

## My first figure of the Gapminder data

```{r gapminder 3.4}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point()
```

## Working on additional figures


```{r figure 3.5}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_smooth()
```
```{r figure 3.6}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() + geom_smooth()
```
```{r figure 3.7}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() + geom_smooth(method = "lm")
```
```{r figure 3.8}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() + geom_smooth(method = "lm") +
scale_x_log10()
```
```{r figure 3.9}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))
p + geom_point() + geom_smooth(method = "lm") +
scale_x_log10(labels = scales ::dollar)
```
```{r figure 3.10}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = "purple"))
p + geom_point() + geom_smooth(method = "lm") +
scale_x_log10(labels = scales ::dollar)
```
```{r figure 3.11}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp,))

p + geom_point(color = "purple") + 
  geom_smooth(method = "loess") +
scale_x_log10(labels = scales ::dollar)
```
```{r figure 3.12}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp,))

p + geom_point(alpha = 0.3) + 
  geom_smooth(color = "orange", se = FALSE, size = 8,method = "lm") +
scale_x_log10(labels = scales ::dollar)
```
```{r figure 3.13}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp,))

p + geom_point(alpha = 0.3) + 
  geom_smooth(method = "lm") +
scale_x_log10(labels = scales ::dollar)+
  labs(x = "GDP per Capita",
       y = "life Expectancy in Years",
       title = "Economic Growth and Life Expectancy", 
       caption = "Source: Gapminder.")
      
```

```{r figure 3.14}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = continent,
                          fill = continent))

p + geom_point() +
  geom_smooth(method = "loess") +
scale_x_log10(labels = scales ::dollar)+
  labs(x = "GDP per Capita",
       y = "life Expectancy in Years",
       title = "Economic Growth and Life Expectancy", 
       caption = "Source: Gapminder.")
    

```
```{r figure 3.15}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))

p + geom_point(mapping = aes(color = continent,
                          fill = continent)) +
  geom_smooth(method = "loess") +
scale_x_log10(labels = scales ::dollar)+
  labs(x = "GDP per Capita",
       y = "life Expectancy in Years",
       title = "Economic Growth and Life Expectancy", 
       caption = "Source: Gapminder.")
      
```
```{r figure 3.16}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap,
                          y = lifeExp))

p + geom_point(mapping = aes(color = log(pop))) +
  geom_smooth(method = "loess") + 
scale_x_log10(labels = scales ::dollar)+
  labs(x = "GDP per Capita",
       y = "life Expectancy in Years",
       title = "Economic Growth and Life Expectancy", 
       caption = "Source: Gapminder.")
      
```